services:
  pdb:
    container_name: pdb6
    image: postgres:16.2-alpine3.19
    environment:
      POSTGRES_DB: "itm-db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - itm-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d itm-db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - itm-network

volumes:
  itm-db:
    driver: local
    driver_opts:
#      type: tmpfs
#      device: tmpfs
      type: "none"
      o: "bind"
      device: ./pdb

networks:
  itm-network:
    driver: bridge
